### ISSUE TITLE
I am A beginner. When I practice according to README_sdxl，1. Train LoRAs for subject/style images, I encounter an error. Please help me

### ISSUE THREAD

**Issue by julyao-yph** [mkshing/ziplora-pytorch#18]
The error information is as follows：
Traceback (most recent call last):
File "train_dreambooth_lora_sdxl.py", line 1760, in
main(args)
File "train_dreambooth_lora_sdxl.py", line 919, in main
repo_id = create_repo(
File "D:\app_download\anaconda\envs\ziplora1\lib\site-packages\huggingface_hub\utils_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
return _run_code(code, main_globals, None,
File "D:\app_download\anaconda\envs\ziplora1\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "D:\app_download\anaconda\envs\ziplora1\Scripts\accelerate.exe_main.py", line 7, in
File "D:\app_download\anaconda\envs\ziplora1\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
args.func(args)
File "D:\app_download\anaconda\envs\ziplora1\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
simple_launcher(args)
File "D:\app_download\anaconda\envs\ziplora1\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\app_download\anaconda\envs\ziplora1\python.exe', 'train_dreambooth_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--instance_data_dir
=dog', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--output_dir=lora-trained-xl', '--mixed_precision=fp16', '--instance_prompt=a photo of sks dog', '--resolution=1024', '--train_batch_size=1', '--gradie
nt_accumulation_steps=4', '--learning_rate=1e-5', '--report_to=wandb', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=50', '--validation_prompt=A photo of sks dog in a bucket', '--validation_epochs=25', '--
seed=0', '--push_to_hub']' returned non-zero exit status 1.

**Comment by chenxinli001** [comment]
You can use non-disributed training mode to debug, so that the real bug will be printed
